# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'demo_pods' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  use_modular_headers!

  # Pods for demo_pods

  pod 'KinEcosystem', '0.5.4'
  pod 'JWT', '3.0.0-beta.11'
  pod 'Alamofire'

end

