# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

use_frameworks!
use_modular_headers!

workspace 'demo_pods.xcworkspace'

def shared_pods
  pod 'KinEcosystem', '0.5.6'
  pod 'JWT', '3.0.0-beta.11'
  pod 'Alamofire'
end

target 'demo_pods' do
  shared_pods

  target 'RNKin' do
    project '../node_modules/react-native-kin/ios/RNKin.xcodeproj'
    inherit! :search_paths
  end
end
