platform :ios, '9.0'

target 'demo' do
  # need this to use swift in the kin library
  use_modular_headers!

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    # Add any other subspecs you want to use in your project
  ]

  pod 'react-native-kin', :path => '../node_modules/react-native-kin'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        # workaround for "archive", otherwise it would fail with duplicate react/yoga libs
        # https://github.com/facebook/react-native/issues/12814
        # couldnt fix it better :(
        if target.name == "React"
            target.remove_from_project
        end
        if target.name == "yoga"
            target.remove_from_project
        end
    end
end
